version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: ShootingAcademy/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DebugConnection=Host=database;Port=5432;Database=SOSALDB;Username=admin;Password=root
    depends_on:
      - database

  database:
    image: postgres:15
    environment:
      POSTGRES_DB: ALEXYS
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: